---
- hosts: localhost
  tasks:
    - name: Create dedicated user
      user:
        name: hackaton
        createhome: no
      become: yes

    - name: Install java
      apt:
        update_cache: yes
        name: openjdk-8-jdk
        state: present
      become: yes

    - name: Create application directory
      file:
        group: hackaton
        owner: hackaton
        path: /opt/hackaton
        mode: 640
        state: directory
      become: yes

    - name: Copy application to its directory
      copy:
        src: /var/tmp/jenkins-kata-1.0-SNAPSHOT.jar
        dest: /opt/hackaton/jenkins-kata-1.0-SNAPSHOT.jar
        owner: hackaton
        group: hackaton
        mode: 640
      become: yes
